PIHOLE_ENABLED: true
PIHOLE_URL: 'http://192.168.1.10:8084'
PIHOLE_PASSWORD: 'password' # "" if no password is set on Pi-hole
SCHEDULER_INTERVAL_MINUTES: 1 # Interval in minutes for scheduled job
NPM_URL: 'http://192.168.1.10:81'
NPM_USERNAME: 'admin1@example.com'
NPM_PASSWORD: 'Password'
NPM_ENABLED: true
NPM_DEFAULTS:
  forward_scheme: 'http'
  certificate_name: "*.mp-studio.duckdns.org"
#  access_list_name": 'ACL-HOME'
  block_exploits: true
  caching_enabled: false
  ssl_forced: true
  http2_support: true
  hsts_enabled: true
  hsts_subdomains: true
  allow_websocket_upgrade: true
PIHOLE_DEFAULTS:
  pihole_type: 'cname' # or dns
  cname_target: 'npm.mp-studio.duckdns.org'
#DOCKER_TCP_URL: 'tcp://192.168.1.30:2375' # Docker host URL for remote API access, if not set, local socket will be used